routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('compro.home.index');
});

Route::get('/santri', function () {
    return view('admin.dashboard.index');
});


Route::get('/', 'ComproController@home')->name('compro.home');
Route::get('/contact-us', 'ComproController@contact')->name('compro.contact');

Route::get('/about-ppm-afm', function () {
    return view('compro.about.index');
})->name('compro.about');

Route::get('/team', function () {
    return view('compro.team.index');
})->name('compro.team');


Route::get('/coba', 'PercobaanController@index');
Route::resource('poin', 'Admin\PoinController');
Route::post('/poin/import_excel', 'PoinController@import_excel');

Route::get('/cobanih', 'CobaController@index');
Route::get("/santri/datasantri", 'DataSantriController@index')->name('santri.index');
Route::get("/santri/datasantri/create_data", 'DataSantriController@masukcreate');
Route::post("/santri/datasantri/create_data", 'DataSantriController@create')->name("santri.create");
Route::get("/santri/datasantri/{id}/edit", "DataSantriController@edit");
Route::post("/santri/datasantri/{id}/update", "DataSantriController@update")->name("santri.update");
Route::get("/santri/datasantri/{id}/delete", "DataSantriController@delete");
Route::post('/santri/datasantri/import_excel', 'DataSantriController@importexcel')->name('santri.import');

Route::get("/santri/datasantri/{id}/profile", "DataSantriController@profile");

Route::get('/berita','BeritaController@index');
Route::get('/buat','BeritaController@buat');
Route::POST('/berita/create','BeritaController@create');
Route::get('/berita/{id}/edit', 'BeritaController@edit');
Route::post('/berita/{id}/update','BeritaController@update');
Route::get('/berita/{id}/delete', 'BeritaController@delete' );
Route::get('/berita/{id}/view', 'BeritaController@view')->name('berita.show');
Route::get('/berita/list-berita','BeritaController@list')->name('berita.list');

resources/views/includes/admin/footer.blade.php
<footer class="footer">
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-6">
                <script>
                    document.write(new Date().getFullYear())
                </script> © PPM Al-Faqih Mandiri.
            </div>
            <div class="col-sm-6">
                <div class="text-sm-end d-none d-sm-block">
                    Design & Develop by Themesbrand
                </div>
            </div>
        </div>
    </div>
</footer>

resources/views/includes/admin/header.blade.php
<header id="page-topbar">
    <div class="navbar-header">
        <div class="container-fluid">
            <div class="float-end">

                <div class="dropdown d-inline-block">
                    <button type="button" class="btn header-item waves-effect"
                        id="page-header-user-dropdown" data-bs-toggle="dropdown" aria-haspopup="true"
                        aria-expanded="false">
                        <img class="rounded-circle header-profile-user"
                            src="{{ asset('assets/dashboards/images/users/avatar-2.jpg') }}" alt="Header Avatar">
                        <span class="d-none d-xl-inline-block ms-1">Catur Satria</span>
                        <i class="mdi mdi-chevron-down d-none d-xl-inline-block"></i>
                    </button>
                    <div class="dropdown-menu dropdown-menu-end">
                        <!-- item-->
                        <a class="dropdown-item" href="#"><i
                                class="bx bx-user font-size-16 align-middle me-1"></i>
                            Profile</a>
                        {{-- <a class="dropdown-item" href="#"><i
                                class="bx bx-wallet font-size-16 align-middle me-1"></i> My
                            Wallet</a>
                        <a class="dropdown-item d-block" href="#"><span
                                class="badge bg-success float-end">11</span><i
                                class="bx bx-wrench font-size-16 align-middle me-1"></i> Settings</a>
                        <a class="dropdown-item" href="#"><i
                                class="bx bx-lock-open font-size-16 align-middle me-1"></i>
                            Lock screen</a> --}}
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item text-danger" href="#"><i
                                class="bx bx-power-off font-size-16 align-middle me-1 text-danger"></i>
                            Logout</a>
                    </div>
                </div>

                {{-- <div class="dropdown d-inline-block">
                    <button type="button" class="btn header-item noti-icon right-bar-toggle waves-effect">
                        <i class="mdi mdi-settings-outline"></i>
                    </button>
                </div> --}}

            </div>
            <div>
                <!-- LOGO -->
                <div class="navbar-brand-box">
                    <a href="index.html" class="logo logo-dark">
                        <span class="logo-sm">
                            <img src="{{ asset('assets/dashboards/images/logo-sm.png')}}" alt="" height="20">
                        </span>
                        <span class="logo-lg">
                            <img src="{{ asset('assets/dashboards/images/logo-dark.png')}}" alt="" height="17">
                        </span>
                    </a>

                    <a href="index.html" class="logo logo-light">
                        <span class="logo-sm">
                            <img src="{{ asset('assets/dashboards/images/logo-sm.png')}}" alt="" height="20">
                        </span>
                        <span class="logo-lg">
                            <img src="{{ asset('assets/dashboards/images/logo-light.png')}}" alt="" height="19">
                        </span>
                    </a>
                </div>

                <button type="button"
                    class="btn btn-sm px-3 font-size-16 header-item toggle-btn waves-effect"
                    id="vertical-menu-btn">
                    <i class="fa fa-fw fa-bars"></i>
                </button>
            </div>

        </div>
    </div>
</header>

resources/views/includes/admin/script.blade.php
<!-- JAVASCRIPT -->
<script src="{{ asset('assets/dashboards/libs/jquery/jquery.min.js') }}"></script>
<script src="{{ asset('assets/dashboards/libs/bootstrap/js/bootstrap.bundle.min.js') }}"></script>
<script src="{{ asset('assets/dashboards/libs/metismenu/metisMenu.min.js') }}"></script>
<script src="{{ asset('assets/dashboards/libs/simplebar/simplebar.min.js') }}"></script>
<script src="{{ asset('assets/dashboards/libs/node-waves/waves.min.js') }}"></script>
<script src="{{ asset('assets/dashboards/libs/jquery-sparkline/jquery.sparkline.min.js') }}"></script>


<!-- Required datatable js -->
<script src="{{ asset('assets/dashboards/libs/datatables.net/js/jquery.dataTables.min.js') }}"></script>
<script src="{{ asset('assets/dashboards/libs/datatables.net-bs4/js/dataTables.bootstrap4.min.js') }}"></script>
<!-- Buttons examples -->
<script src="{{ asset('assets/dashboards/libs/datatables.net-buttons/js/dataTables.buttons.min.js') }}"></script>
<script src="{{ asset('assets/dashboards/libs/datatables.net-buttons-bs4/js/buttons.bootstrap4.min.js') }}"></script>
<script src="{{ asset('assets/dashboards/libs/jszip/jszip.min.js') }}"></script>
<script src="{{ asset('assets/dashboards/libs/pdfmake/build/pdfmake.min.js') }}"></script>
<script src="{{ asset('assets/dashboards/libs/pdfmake/build/vfs_fonts.js') }}"></script>
<script src="{{ asset('assets/dashboards/libs/datatables.net-buttons/js/buttons.html5.min.js') }}"></script>
<script src="{{ asset('assets/dashboards/libs/datatables.net-buttons/js/buttons.print.min.js') }}"></script>
<script src="{{ asset('assets/dashboards/libs/datatables.net-buttons/js/buttons.colVis.min.js') }}"></script>
<!-- Responsive examples -->
<script src="{{ asset('assets/dashboards/libs/datatables.net-responsive/js/dataTables.responsive.min.js') }}"></script>
<script src="{{ asset('assets/dashboards/libs/datatables.net-responsive-bs4/js/responsive.bootstrap4.min.js') }}"></script>

<!-- Datatable init js -->
<script src="{{ asset('assets/dashboards/js/pages/datatables.init.js') }}"></script>

<!-- App js -->
<<<<<<< HEAD
<script src="{{ asset('assets/dashboards/js/app.js')}}"></script>
=======
<script src="{{ asset('assets/dashboards/js/app.js') }}"></script>

>>>>>>> 6f56a9e9745fcf6740b3a565c25a1d1145379f40

resources/views/includes/admin/sidebar.blade.php
<div class="vertical-menu">
    <div class="h-100">

        <div class="user-wid text-center py-4">
            <div class="user-img">
                <img src="{{ asset('assets/dashboards/images/users/avatar-2.jpg')}}" alt="" class="avatar-md mx-auto rounded-circle">
            </div>

            <div class="mt-3">

                <a href="#" class="text-dark fw-medium font-size-16">Catur Satria</a>
                <p class="text-body mt-1 mb-0 font-size-13">Santri</p>

            </div>
        </div>

        <!--- Sidemenu -->
        <div id="sidebar-menu">
            <!-- Left Menu Start -->
            <ul class="metismenu list-unstyled" id="side-menu">
                <li class="menu-title">Menu</li>

                <li>
                    <a href="javascript: void(0);" class="waves-effect">
                        <i class="mdi mdi-airplay"></i><span
                            class="badge rounded-pill bg-info float-end">2</span>
                        <span>Dashboard</span>
                    </a>
                    {{-- <ul class="sub-menu" aria-expanded="false">
                        <li><a href="index.html">Dashboard 1</a></li>
                        <li><a href="index-2.html">Dashboard 2</a></li>
                    </ul> --}}
                </li>

                <li class="{{ (request()->is('santri/datasantri*')) ? 'mm-active' : '' }}">
                    <a href="{{ route('santri.index') }}" class=" waves-effect {{ (request()->is('santri/datasantri*')) ? 'active' : '' }}">
                        <i class="mdi mdi-table-headers-eye"></i>
                        <span>Data Santri</span>
                    </a>
                </li>

                <li class="{{ (request()->is('poin-santri*')) ? 'mm-active' : '' }}">
                    <a href="{{ route('poin.index') }}" class=" waves-effect" {{ (request()->is('poin-santri*')) ? 'active' : '' }}>
                        <i class="mdi mdi-table-headers-eye"></i>
                        <span>Monitor Poin</span>
                    </a>
                </li>

                <li>
                    <a href="calendar.html" class=" waves-effect">
                        <i class="mdi mdi-equalizer-outline"></i>
                        <span>Monitor Kuantitas Materi</span>
                    </a>
                </li>

            </ul>
        </div>
        <!-- Sidebar -->
    </div>
</div>

resources/views/includes/admin/style.blade.php
<!-- App favicon -->
<link rel="shortcut icon" href="{{ asset('assets/dashboards/images/favicon.ico') }}">

<!-- Bootstrap Css -->
<link href="{{ asset('assets/dashboards/css/bootstrap.min.css') }}" id="bootstrap-style" rel="stylesheet" type="text/css" />
<!-- Icons Css -->
<link href="{{ asset('assets/dashboards/css/icons.min.css') }}" rel="stylesheet" type="text/css" />
<!-- App Css-->
<link href="{{ asset('assets/dashboards/css/app.min.css') }}" id="app-style" rel="stylesheet" type="text/css" />


    <!-- DataTables -->
    <link href="{{ asset('assets/dashboards/libs/datatables.net-bs4/css/dataTables.bootstrap4.min.css') }}" rel="stylesheet" type="text/css" />
    <link href="{{ asset('assets/dashboards/libs/datatables.net-buttons-bs4/css/buttons.bootstrap4.min.css') }}" rel="stylesheet"
        type="text/css" />

    <!-- Responsive datatable examples -->
    <link href="{{ asset('assets/dashboards/libs/datatables.net-responsive-bs4/css/responsive.bootstrap4.min.css') }}" rel="stylesheet"
        type="text/css" />